name: Run and Collect Tests
description: Run a test suite, capture exit code, and upload artifacts
inputs:
  id:
    required: true
    description: Short identifier for this test run
  config:
    required: true
    description: Path to .properties config file
  tag:
    required: true
    description: Cucumber tag filter for this run
  platform:
    required: true
    description: Platform (e.g. web, android, api)
  applitools_api_key:
    required: true
    description: Applitools API Key
  browserstack_username:
    required: true
    description: BrowserStack username
  browserstack_key:
    required: true
    description: BrowserStack access key

outputs:
  exit_code:
    description: The exit code from the test execution

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "🔧 Running tests for ${{ inputs.id }}"
        set +e
        RUN_IN_CI=true \
        CONFIG=${{ inputs.config }} \
        PLATFORM=${{ inputs.platform }} \
        TAG=${{ inputs.tag }} \
        TESWIZ_APPLITOOLS_API_KEY=${{ inputs.applitools_api_key }} \
        CLOUD_USERNAME=${{ inputs.browserstack_username }} \
        CLOUD_KEY=${{ inputs.browserstack_key }} \
        ./gradlew run
        echo "exit_code=$?" >> "$GITHUB_OUTPUT"

    - name: Upload Test Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ inputs.id }}
        path: target
