name: Run and Collect Tests

description: >
  Composite action to run test suites with specified tags, config, and environment, collect the exit code,
  and upload artifacts from the target/ directory.

inputs:
  id:
    required: true
    description: Short identifier for the test suite (used in logs and artifact naming)
  config-path:
    required: true
    description: Path to the test configuration .properties file
  tag:
    required: true
    description: Cucumber tag to execute (e.g. @smoke and @web)
  platform:
    required: true
    description: Platform under test (e.g. web, android, api)
  applitools_api_key:
    required: true
    description: Applitools API Key
  browserstack_username:
    required: true
    description: BrowserStack username
  browserstack_key:
    required: true
    description: BrowserStack access key
  display-name:
    required: true
    description: Friendly name for logs (e.g. "PDF Web Tests")
  artifact-name:
    required: true
    description: Name of the artifact to be saved
  is-visual:
    required: true
    description: Whether to enable visual testing (true or false)
  additional-env:
    required: false
    description: Additional environment variables (space-separated)

outputs:
  exit_code:
    description: Exit code from test execution
    value: ${{ steps.run-tests.outputs.exit_code }}

runs:
  using: "composite"
  steps:
    - id: run-tests
      shell: bash
      run: |
        set +e
        echo "🧪 Running ${{ inputs.display-name }}"
        export APPLITOOLS_API_KEY="${{ inputs.applitools_api_key }}"
        export CLOUD_USERNAME="${{ inputs.browserstack_username }}"
        export CLOUD_KEY="${{ inputs.browserstack_key }}"
        export IS_VISUAL="${{ inputs.is-visual }}"
        export PLATFORM="${{ inputs.platform }}"
        export CONFIG="${{ inputs.config-path }}"
        export TAG="${{ inputs.tag }}"

        if [[ -n "${{ inputs.additional-env }}" ]]; then
          echo "Setting additional environment: ${{ inputs.additional-env }}"
          eval "export ${{ inputs.additional-env }}"
        fi

        ./gradlew run
        echo "exit_code=$?" >> "$GITHUB_OUTPUT"
        
        EXIT_CODE=0
        RUN_IN_CI=true TESWIZ_APPLITOOLS_API_KEY="${{ inputs.applitools_api_key }}" CLOUD_USERNAME="${{ inputs.browserstack_username }}" CLOUD_KEY="${{ inputs.browserstack_key }}" PLATFORM="${{ inputs.platform }}"         TAG="${{ inputs.tag }}" CONFIG="${{ inputs.config-path }}" IS_VISUAL="${{ inputs.is-visual }}" ${{ inputs.additional-env }} ./gradlew run || EXIT_CODE=$?
        echo "exit_code=$EXIT_CODE" >> "$GITHUB_OUTPUT"

    - name: Upload ${{ inputs.display-name }} Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: target
